name:                   Check substrate@master

on:
  schedule:             # Weekly build
    - cron:             '0 0 * * SAT'
jobs:
  check-and-test:
    name:                          Check and test
    runs-on:                       ubuntu-latest
    steps:
      -
        name:                      Cancel Previous Runs
        uses:                      styfle/cancel-workflow-action@0.4.1
        with:
          access_token:            ${{ github.token }}
      -
        name:                      Checkout sources & submodules
        uses:                      actions/checkout@v2
        with:
          fetch-depth:             5
          submodules:              true
      -
        name:                      Install rust nightly
        uses:                      actions-rs/toolchain@v1
        with:
          toolchain:               nightly-2021-03-03
          target:                  wasm32-unknown-unknown
          override:                false
      -
        name:                      Checking evercity
        uses:                      actions-rs/cargo@master
        with:
          command:                 check
          args:                    --all  --verbose
      -
        name:                      Update  substrate
        uses:                      actions-rs/cargo@master
        with:
          command:                 update
      -
        name:                      Checking substrate
        uses:                      actions-rs/cargo@master
        with:
          command:                 check
          args:                    --all  --verbose
      -
        name:                      Testing rust
        uses:                      actions-rs/cargo@master
        with:
          command:                 test
          args:                    --all  --verbose
