name:                   Check substrate@master

on:
  schedule:             # Weekly build
    - cron:             '0 0 * * SAT'
jobs:
  check-and-test:
    name:                          Check and test
    runs-on:                       self-hosted
    container:
      image:                       paritytech/ci-linux:production
      volumes:
        - /cache:/cache
    env:
      RUST_BACKTRACE:              full
      CARGO_TARGET_DIR:            /cache/master
      SCCACHE_REDIS:               redis://172.17.0.1/0
      SCCACHE_IDLE_TIMEOUT:        0
      CMAKE_C_COMPILER_LAUNCHER:   sccache
      CMAKE_CXX_COMPILER_LAUNCHER: sccache
    steps:
      - name:                      Cancel Previous Runs
        uses:                      styfle/cancel-workflow-action@0.4.1
        with:
          access_token:            ${{ github.token }}
      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@v2
        with:
          ref:                     feature_master_substrate
          fetch-depth:             1
          submodules:              false
      - name:                      Install nightly
        uses:                      actions-rs/toolchain@v1
        with:
            target:                wasm32-unknown-unknown
            components:            rustfmt, clippy
## Check
      - name:                      Checking evercity
        uses:                      actions-rs/cargo@master
        with:
          command:                 check
          args:                    --all  --verbose
      - name:                      Update  substrate
        uses:                      actions-rs/cargo@master
        with:
          command:                 update
      - name:                      Checking substrate
        uses:                      actions-rs/cargo@master
        with:
          command:                 check
          args:                    --all  --verbose
## Test
      - name:                      Testing rust
        uses:                      actions-rs/cargo@master
        with:
          command:                 test
          args:                    --all  --verbose
